/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorsBrowseRouteImport } from './routes/authors.browse'
import { Route as AuthorsBrowseByLetterLetterRouteImport } from './routes/authors.browse.by-letter.$letter'
import { Route as AuthorsBrowseByLetterLetterAuthorRouteImport } from './routes/authors.browse.by-letter.$letter.$author'

const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsBrowseRoute = AuthorsBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthorsRoute,
} as any)
const AuthorsBrowseByLetterLetterRoute =
  AuthorsBrowseByLetterLetterRouteImport.update({
    id: '/by-letter/$letter',
    path: '/by-letter/$letter',
    getParentRoute: () => AuthorsBrowseRoute,
  } as any)
const AuthorsBrowseByLetterLetterAuthorRoute =
  AuthorsBrowseByLetterLetterAuthorRouteImport.update({
    id: '/$author',
    path: '/$author',
    getParentRoute: () => AuthorsBrowseByLetterLetterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/authors/browse': typeof AuthorsBrowseRouteWithChildren
  '/authors/browse/by-letter/$letter': typeof AuthorsBrowseByLetterLetterRouteWithChildren
  '/authors/browse/by-letter/$letter/$author': typeof AuthorsBrowseByLetterLetterAuthorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/authors/browse': typeof AuthorsBrowseRouteWithChildren
  '/authors/browse/by-letter/$letter': typeof AuthorsBrowseByLetterLetterRouteWithChildren
  '/authors/browse/by-letter/$letter/$author': typeof AuthorsBrowseByLetterLetterAuthorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/authors/browse': typeof AuthorsBrowseRouteWithChildren
  '/authors/browse/by-letter/$letter': typeof AuthorsBrowseByLetterLetterRouteWithChildren
  '/authors/browse/by-letter/$letter/$author': typeof AuthorsBrowseByLetterLetterAuthorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authors'
    | '/authors/browse'
    | '/authors/browse/by-letter/$letter'
    | '/authors/browse/by-letter/$letter/$author'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authors'
    | '/authors/browse'
    | '/authors/browse/by-letter/$letter'
    | '/authors/browse/by-letter/$letter/$author'
  id:
    | '__root__'
    | '/'
    | '/authors'
    | '/authors/browse'
    | '/authors/browse/by-letter/$letter'
    | '/authors/browse/by-letter/$letter/$author'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorsRoute: typeof AuthorsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/browse': {
      id: '/authors/browse'
      path: '/browse'
      fullPath: '/authors/browse'
      preLoaderRoute: typeof AuthorsBrowseRouteImport
      parentRoute: typeof AuthorsRoute
    }
    '/authors/browse/by-letter/$letter': {
      id: '/authors/browse/by-letter/$letter'
      path: '/by-letter/$letter'
      fullPath: '/authors/browse/by-letter/$letter'
      preLoaderRoute: typeof AuthorsBrowseByLetterLetterRouteImport
      parentRoute: typeof AuthorsBrowseRoute
    }
    '/authors/browse/by-letter/$letter/$author': {
      id: '/authors/browse/by-letter/$letter/$author'
      path: '/$author'
      fullPath: '/authors/browse/by-letter/$letter/$author'
      preLoaderRoute: typeof AuthorsBrowseByLetterLetterAuthorRouteImport
      parentRoute: typeof AuthorsBrowseByLetterLetterRoute
    }
  }
}

interface AuthorsBrowseByLetterLetterRouteChildren {
  AuthorsBrowseByLetterLetterAuthorRoute: typeof AuthorsBrowseByLetterLetterAuthorRoute
}

const AuthorsBrowseByLetterLetterRouteChildren: AuthorsBrowseByLetterLetterRouteChildren =
  {
    AuthorsBrowseByLetterLetterAuthorRoute:
      AuthorsBrowseByLetterLetterAuthorRoute,
  }

const AuthorsBrowseByLetterLetterRouteWithChildren =
  AuthorsBrowseByLetterLetterRoute._addFileChildren(
    AuthorsBrowseByLetterLetterRouteChildren,
  )

interface AuthorsBrowseRouteChildren {
  AuthorsBrowseByLetterLetterRoute: typeof AuthorsBrowseByLetterLetterRouteWithChildren
}

const AuthorsBrowseRouteChildren: AuthorsBrowseRouteChildren = {
  AuthorsBrowseByLetterLetterRoute:
    AuthorsBrowseByLetterLetterRouteWithChildren,
}

const AuthorsBrowseRouteWithChildren = AuthorsBrowseRoute._addFileChildren(
  AuthorsBrowseRouteChildren,
)

interface AuthorsRouteChildren {
  AuthorsBrowseRoute: typeof AuthorsBrowseRouteWithChildren
}

const AuthorsRouteChildren: AuthorsRouteChildren = {
  AuthorsBrowseRoute: AuthorsBrowseRouteWithChildren,
}

const AuthorsRouteWithChildren =
  AuthorsRoute._addFileChildren(AuthorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorsRoute: AuthorsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
